package org.omg.IOP;


/**
* org/omg/IOP/RMICustomMaxStreamFormat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-x64-cygwin-sans-NAS/jdk8u391/514/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Wednesday, October 4, 2023 7:55:23 AM UTC
*/

public interface RMICustomMaxStreamFormat
{

  /**
     * Identifies a CDR encapsulation of the RMICustomMaxStreamFormat
     * service context which contains a single byte specifying
     * the client's maximum RMI-IIOP stream format version.
     *
     * See Java to IDL ptc/02-01-12 1.4.12.
     */
  public static final int value = (int)(17L);
}
