package org.omg.IOP;


/**
* org/omg/IOP/TAG_POLICIES.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-x64-cygwin-sans-NAS/jdk8u391/514/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Wednesday, October 4, 2023 7:55:23 AM UTC
*/

public interface TAG_POLICIES
{

  /**
     * A profile component containing the sequence of QoS policies exported
     * with the object reference by an object adapter.
     */
  public static final int value = (int)(2L);
}
