package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/Repository.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-x64-cygwin-sans-NAS/jdk8u391/514/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Wednesday, October 4, 2023 7:55:23 AM UTC
*/

public interface Repository extends RepositoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Repository
