package org.omg.PortableServer;


/**
* org/omg/PortableServer/THREAD_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-x64-cygwin-sans-NAS/jdk8u391/514/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Wednesday, October 4, 2023 7:55:24 AM UTC
*/

public interface THREAD_POLICY_ID
{

  /**
	 * The value representing THREAD_POLICY_ID.
	 */
  public static final int value = (int)(16L);
}
